// VisaCheck Quick Check — pre-filled answer profiles for popular routes.
// Lets users skip the wizard and see results instantly for common scenarios.
// Pure data module — no I/O, no React, no storage.

import type { Answers } from '@/lib/rules-data';

export interface QuickCheckProfile {
  id: string;
  label: { en: string; ur: string; bn: string };
  description: { en: string; ur: string; bn: string };
  countryIso: string;
  categoryId: string;
  nationality: string;
  emoji: string;
  answers: Partial<Answers>;
}

export const QUICK_CHECK_PROFILES: QuickCheckProfile[] = [
  {
    id: 'india-uk-sw',
    label: {
      en: 'India → UK Skilled Worker',
      ur: 'بھارت → برطانیہ ہنر مند کارکن',
      bn: 'ভারত → যুক্তরাজ্য দক্ষ কর্মী',
    },
    description: {
      en: 'IT professional with CoS, £42k salary, B1 English, maintenance certified.',
      ur: 'آئی ٹی پیشہ ور، CoS کے ساتھ، £42k تنخواہ، B1 انگریزی، زرخیز تصدیق شدہ۔',
      bn: 'আইটি পেশাদার, CoS সহ, £42k বেতন, B1 ইংরেজি, রক্ষণাবেক্ষণ প্রত্যয়িত।',
    },
    countryIso: 'GB',
    categoryId: 'skilled_worker',
    nationality: 'India',
    emoji: '🇮🇳→🇬🇧',
    answers: {
      nationality: 'India',
      applyingFromOutsideUK: true,
      jobTitle: 'Software engineer',
      socCode: '2133',
      salary: 42000,
      hasCos: true,
      sponsorLicensed: 'yes',
      newEntrant: false,
      englishMet: true,
      fundsMet: true,
      ihsAware: true,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'nigeria-us-student',
    label: {
      en: 'Nigeria → US Student (F-1)',
      ur: 'نائجیریا → امریکہ طالب علم (F-1)',
      bn: 'নাইজেরিয়া → যুক্তরাষ্ট্র ছাত্র (F-1)',
    },
    description: {
      en: 'Graduate student with I-20, $35k funds, B1 English, valid passport.',
      ur: 'گریجویٹ طالب علم، I-20 کے ساتھ، $35k فنڈز، B1 انگریزی، درست پاسپورٹ۔',
      bn: 'স্নাতক ছাত্র, I-20 সহ, $35k তহবিল, B1 ইংরেজি, বৈধ পাসপোর্ট।',
    },
    countryIso: 'US',
    categoryId: 'student',
    nationality: 'Nigeria',
    emoji: '🇳🇬→🇺🇸',
    answers: {
      nationality: 'Nigeria',
      applyingFromOutsideUK: true,
      admissionOffer: true,
      studyFundsMet: true,
      hasCos: false,
      sponsorLicensed: 'unsure',
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'philippines-ca-sw',
    label: {
      en: 'Philippines → Canada Express Entry',
      ur: 'فلپائن → کینیڈا ایکسپریس انٹری',
      bn: 'ফিলিপাইন → কানাডা এক্সপ্রেস এন্ট্রি',
    },
    description: {
      en: 'Registered nurse with job offer, CLB 7, $25k funds, medical exam ready.',
      ur: 'رجسٹرڈ نرس، نوکری کی پیشکش کے ساتھ، CLB 7، $25k فنڈز، طریقہ امتحان تیار۔',
      bn: 'নিবন্ধিত নার্স, চাকরির প্রস্তাব সহ, CLB 7, $25k তহবিল, মেডিকেল পরীক্ষা প্রস্তুত।',
    },
    countryIso: 'CA',
    categoryId: 'skilled_worker',
    nationality: 'Philippines',
    emoji: '🇵🇭→🇨🇦',
    answers: {
      nationality: 'Philippines',
      applyingFromOutsideUK: true,
      jobTitle: 'Registered nurse',
      salary: 75000,
      hasCos: true,
      sponsorLicensed: 'yes',
      newEntrant: false,
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'pakistan-ae-investor',
    label: {
      en: 'Pakistan → UAE Investor',
      ur: 'پاکستان → متحدہ عرب امارات سرمایہ کار',
      bn: 'পাকিস্তান → সংযুক্ত আরব আমিরাত বিনিয়োগকারী',
    },
    description: {
      en: 'Business owner investing AED 2M in Dubai property, valid passport.',
      ur: 'کاروباری مالک، دبئی کی جائیداد میں AED 2M کی سرمایہ کاری، درست پاسپورٹ۔',
      bn: 'ব্যবসায়ী মালিক, দুবাই সম্পত্তিতে AED 2M বিনিয়োগ, বৈধ পাসপোর্ট।',
    },
    countryIso: 'AE',
    categoryId: 'investor',
    nationality: 'Pakistan',
    emoji: '🇵🇰→🇦🇪',
    answers: {
      nationality: 'Pakistan',
      applyingFromOutsideUK: true,
      businessPlan: true,
      investmentAmount: 2000000,
      hasCos: false,
      sponsorLicensed: 'unsure',
      englishMet: false,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'uk-au-visitor',
    label: {
      en: 'UK → Australia Visitor',
      ur: 'برطانیہ → آسٹریلیا زائر',
      bn: 'যুক্তরাজ্য → অস্ট্রেলিয়া ভিজিটর',
    },
    description: {
      en: 'Tourist visit, 2 weeks, return ticket, travel insurance, AUD $3k funds.',
      ur: 'سیاحتی دورہ، 2 ہفتے، واپسی ٹکٹ، سفری انشورنس، AUD $3k فنڈز۔',
      bn: 'পর্যটক সফর, ২ সপ্তাহ, ফেরার টিকিট, ভ্রমণ বীমা, AUD $3k তহবিল।',
    },
    countryIso: 'AU',
    categoryId: 'visitor',
    nationality: 'United Kingdom',
    emoji: '🇬🇧→🇦🇺',
    answers: {
      nationality: 'United Kingdom',
      applyingFromOutsideUK: true,
      visitPurposeValid: true,
      returnTicket: true,
      healthInsurance: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'turkey-de-student',
    label: {
      en: 'Turkey → Germany Student',
      ur: 'ترکیہ → جرمنی طالب علم',
      bn: 'তুরস্ক → জার্মানি ছাত্র',
    },
    description: {
      en: 'Engineering student with admission, blocked account €11k, A1 German.',
      ur: 'انجینئرنگ طالب علم، داخلہ کے ساتھ، بلاکڈ اکاؤنٹ €11k، A1 جرمن۔',
      bn: 'প্রকৌশল ছাত্র, ভর্তি সহ, ব্লকড অ্যাকাউন্ট €11k, A1 জার্মান।',
    },
    countryIso: 'DE',
    categoryId: 'student',
    nationality: 'Turkey',
    emoji: '🇹🇷→🇩🇪',
    answers: {
      nationality: 'Turkey',
      applyingFromOutsideUK: true,
      admissionOffer: true,
      studyFundsMet: true,
      hasCos: false,
      sponsorLicensed: 'unsure',
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'china-au-visitor',
    label: {
      en: 'China → Australia Visitor',
      ur: 'چین → آسٹریلیا زائر',
      bn: 'চীন → অস্ট্রেলিয়া ভিজিটর',
    },
    description: {
      en: 'Family visit, 3 months, return ticket, travel insurance, AUD $5k funds.',
      ur: 'خاندانی دورہ، 3 ماہ، واپسی ٹکٹ، سفری انشورنس، AUD $5k فنڈز۔',
      bn: 'পারিবারিক সফর, ৩ মাস, ফেরার টিকিট, ভ্রমণ বীমা, AUD $5k তহবিল।',
    },
    countryIso: 'AU',
    categoryId: 'visitor',
    nationality: 'China',
    emoji: '🇨🇳→🇦🇺',
    answers: {
      nationality: 'China',
      applyingFromOutsideUK: true,
      visitPurposeValid: true,
      returnTicket: true,
      healthInsurance: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'egypt-de-student',
    label: {
      en: 'Egypt → Germany Student',
      ur: 'مصر → جرمنی طالب علم',
      bn: 'মিশর → জার্মানি ছাত্র',
    },
    description: {
      en: 'CS student with admission, blocked account €11k, B1 English.',
      ur: 'سی ایس طالب علم، داخلہ کے ساتھ، بلاکڈ اکاؤنٹ €11k، B1 انگریزی۔',
      bn: 'সিএস ছাত্র, ভর্তি সহ, ব্লকড অ্যাকাউন্ট €11k, B1 ইংরেজি।',
    },
    countryIso: 'DE',
    categoryId: 'student',
    nationality: 'Egypt',
    emoji: '🇪🇬→🇩🇪',
    answers: {
      nationality: 'Egypt',
      applyingFromOutsideUK: true,
      admissionOffer: true,
      studyFundsMet: true,
      hasCos: false,
      sponsorLicensed: 'unsure',
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'brazil-ca-sk',
    label: {
      en: 'Brazil → Canada Express Entry',
      ur: 'برازل → کینیڈا ایکسپریس انٹری',
      bn: 'ব্রাজিল → কানাডা এক্সপ্রেস এন্ট্রি',
    },
    description: {
      en: 'Software developer, CLB 8, $20k funds, ECA assessment done.',
      ur: 'سافٹ ویئر ڈویلپر، CLB 8، $20k فنڈز، ECA تشخیص مکمل۔',
      bn: 'সফটওয়্যার ডেভেলপার, CLB 8, $20k তহবিল, ECA মূল্যায়ন সম্পন্ন।',
    },
    countryIso: 'CA',
    categoryId: 'skilled_worker',
    nationality: 'Brazil',
    emoji: '🇧🇷→🇨🇦',
    answers: {
      nationality: 'Brazil',
      applyingFromOutsideUK: true,
      jobTitle: 'Software developer',
      salary: 85000,
      hasCos: true,
      sponsorLicensed: 'yes',
      newEntrant: false,
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'india-sg-sw',
    label: {
      en: 'India → Singapore Skilled Worker',
      ur: 'بھارت → سنگاپور ہنر مند کارکن',
      bn: 'ভারত → সিঙ্গাপুর দক্ষ কর্মী',
    },
    description: {
      en: 'Software engineer, Employment Pass, SGD $6k/month, B1 English.',
      ur: 'سافٹ ویئر انجینئر، ایمپلائمنٹ پاس، SGD $6k/ماہ، B1 انگریزی۔',
      bn: 'সফটওয়্যার ইঞ্জিনিয়ার, এমপ্লয়মেন্ট পাস, SGD $6k/মাস, B1 ইংরেজি।',
    },
    countryIso: 'SG',
    categoryId: 'skilled_worker',
    nationality: 'India',
    emoji: '🇮🇳→🇸🇬',
    answers: {
      nationality: 'India',
      applyingFromOutsideUK: true,
      jobTitle: 'Software engineer',
      salary: 72000,
      hasCos: true,
      sponsorLicensed: 'yes',
      newEntrant: false,
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'china-nz-student',
    label: {
      en: 'China → New Zealand Student',
      ur: 'چین → نیوزی لینڈ طالب علم',
      bn: 'চীন → নিউজিল্যান্ড ছাত্র',
    },
    description: {
      en: 'Postgraduate student, offer of place, NZD $20k funds, IELTS 6.5.',
      ur: 'پوسٹ گریجویٹ طالب علم، جگہ کی پیشکش، NZD $20k فنڈز، IELTS 6.5۔',
      bn: 'স্নাতকোত্তর ছাত্র, স্থানের প্রস্তাব, NZD $20k তহবিল, IELTS 6.5।',
    },
    countryIso: 'NZ',
    categoryId: 'student',
    nationality: 'China',
    emoji: '🇨🇳→🇳🇿',
    answers: {
      nationality: 'China',
      applyingFromOutsideUK: true,
      admissionOffer: true,
      studyFundsMet: true,
      hasCos: false,
      sponsorLicensed: 'unsure',
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
  {
    id: 'brazil-ie-sw',
    label: {
      en: 'Brazil → Ireland Critical Skills',
      ur: 'برازل → آئرلینڈ کنجلی ہنر',
      bn: 'ব্রাজিল → আয়ারল্যান্ড ক্রিটিক্যাল স্কিলস',
    },
    description: {
      en: 'Data scientist, job offer €45k, B1 English, degree verified.',
      ur: 'ڈیٹا سائنٹسٹ، نوکری کی پیشکش €45k، B1 انگریزی، ڈگری تصدیق شدہ۔',
      bn: 'ডেটা সায়েন্টিস্ট, চাকরির প্রস্তাব €45k, B1 ইংরেজি, ডিগ্রি যাচাইকৃত।',
    },
    countryIso: 'IE',
    categoryId: 'skilled_worker',
    nationality: 'Brazil',
    emoji: '🇧🇷→🇮🇪',
    answers: {
      nationality: 'Brazil',
      applyingFromOutsideUK: true,
      jobTitle: 'Data scientist',
      salary: 45000,
      hasCos: true,
      sponsorLicensed: 'yes',
      newEntrant: false,
      englishMet: true,
      fundsMet: true,
      ihsAware: false,
      criminalCert: true,
      passportValid: true,
    },
  },
];

export function getQuickCheckProfile(id: string): QuickCheckProfile | undefined {
  return QUICK_CHECK_PROFILES.find((p) => p.id === id);
}
